In [42]:
# from tensorflow.examples.tutorials.mnist import input_data
# mnist = input_data.read_data_sets('MNIST_data', one_hot=True)

%load_ext autoreload
%autoreload 2
    
import reader 
import tensorflow as tf
sess = tf.InteractiveSession()


train = reader.reader('/home/lee/Desktop/rooms')
test = reader.reader('/home/lee/Desktop/rooms_test')


import numpy as np
import random
import cv2
import os
import collections

class learner(object):
    def __init__(self, num_classes, height=28, width=28):
        self.num_classes = num_classes
        self.height = height
        self.width = width
        
        # input and output
        self.input = tf.placeholder(tf.float32, shape=[None, self.height*self.width])
        self.label = tf.placeholder(tf.float32, shape=[None, self.num_classes])
    
    
    def network(self):
        self.network.W = tf.Variable(tf.zeros([self.height*self.width,self.num_classes]))
        self.network.b = tf.Variable(tf.zeros([self.num_classes]))
        
        sess.run(tf.initialize_all_variables())
        y = tf.nn.softmax(tf.matmul(x,W) + b)
        
        cross_entropy = tf.reduce_mean(-tf.reduce_sum(y_ * tf.log(y), reduction_indices=[1]))

        # training
        train_step = tf.train.GradientDescentOptimizer(0.5).minimize(cross_entropy)
        
def weight_variable(shape):
    initial = tf.truncated_normal(shape, stddev=0.1)
    return tf.Variable(initial)

def bias_variable(shape):
    initial = tf.constant(0.1, shape=shape)
    return tf.Variable(initial)

def conv2d(x, W):
    return tf.nn.conv2d(x, W, strides=[1, 1, 1, 1], padding='SAME')

def max_pool_2x2(x):
    return tf.nn.max_pool(x, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding='SAME')


# W_conv1 = weight_variable([5, 5, 1, 32])
# b_conv1 = bias_variable([32])

# x_image = tf.reshape(x, [-1,28,28,1])

# h_conv1 = tf.nn.relu(conv2d(x_image, W_conv1) + b_conv1)
# h_pool1 = max_pool_2x2(h_conv1)

# W_conv2 = weight_variable([5, 5, 32, 64])
# b_conv2 = bias_variable([64])

# h_conv2 = tf.nn.relu(conv2d(h_pool1, W_conv2) + b_conv2)
# h_pool2 = max_pool_2x2(h_conv2)


# W_fc1 = weight_variable([7 * 7 * 64, 1024])
# b_fc1 = bias_variable([1024])

# h_pool2_flat = tf.reshape(h_pool2, [-1, 7*7*64])
# h_fc1 = tf.nn.relu(tf.matmul(h_pool2_flat, W_fc1) + b_fc1)

# keep_prob = tf.placeholder(tf.float32)
# h_fc1_drop = tf.nn.dropout(h_fc1, keep_prob)

# W_fc2 = weight_variable([1024, 10])
# b_fc2 = bias_variable([10])

# y_conv=tf.nn.softmax(tf.matmul(h_fc1_drop, W_fc2) + b_fc2)


# cross_entropy = tf.reduce_mean(-tf.reduce_sum(y_ * tf.log(y_conv), reduction_indices=[1]))
# train_step = tf.train.AdamOptimizer(1e-4).minimize(cross_entropy)
# correct_prediction = tf.equal(tf.argmax(y_conv,1), tf.argmax(y_,1))
# accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
# sess.run(tf.initialize_all_variables())
# for i in range(20000):
#   batch = mnist.train.next_batch(50)
#   if i%100 == 0:
#     train_accuracy = accuracy.eval(feed_dict={
#         x:batch[0], y_: batch[1], keep_prob: 1.0})
#     print("step %d, training accuracy %g"%(i, train_accuracy))
#   train_step.run(feed_dict={x: batch[0], y_: batch[1], keep_prob: 0.5})

# print("test accuracy %g"%accuracy.eval(feed_dict={
#     x: mnist.test.images, y_: mnist.test.labels, keep_prob: 1.0}))


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [43]:
imgHeight = 28
imgWidth = 28
numClasses = train.num_classes()

# input and output
x = tf.placeholder(tf.float32, shape=[None, imgHeight*imgWidth])
y_ = tf.placeholder(tf.float32, shape=[None, numClasses])

# create network
W = tf.Variable(tf.zeros([imgHeight*imgWidth,numClasses]))
b = tf.Variable(tf.zeros([numClasses]))
sess.run(tf.initialize_all_variables())
y = tf.nn.softmax(tf.matmul(x,W) + b)
cross_entropy = tf.reduce_mean(-tf.reduce_sum(y_ * tf.log(y), reduction_indices=[1]))


# training
train_step = tf.train.GradientDescentOptimizer(0.00000005).minimize(cross_entropy)

correct_prediction = tf.equal(tf.argmax(y,1), tf.argmax(y_,1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))


for i in xrange(10000):
    if (i) % 500 == 0: 
        images, labels = test.all()
        print i, (accuracy.eval(feed_dict={x: images, y_: labels}))
        
    batch = train.next_batch(50)
    train_step.run(feed_dict={x: batch[0], y_: batch[1]})
    #print y.eval(feed_dict={x: batch[0]})
    

images, labels = test.all()
print(accuracy.eval(feed_dict={x: images, y_: labels}))

0 0.333333
100 0.533333
200 0.577778
300 0.555556
400 0.577778
500 0.533333
600 0.577778
700 0.555556
800 0.555556
900 0.577778
1000 0.6
1100 0.577778
1200 0.555556
1300 0.577778
1400 0.555556
1500 0.6
1600 0.6
1700 0.533333
1800 0.488889
1900 0.577778
2000 0.555556
2100 0.555556
2200 0.577778
2300 0.555556
2400 0.6
2500 0.555556
2600 0.533333
2700 0.577778
2800 0.533333
2900 0.533333
3000 0.577778
3100 0.6
3200 0.577778
3300 0.555556
3400 0.6
3500 0.6
3600 0.577778
3700 0.577778
3800 0.577778
3900 0.622222
4000 0.6
4100 0.6
4200 0.6
4300 0.577778
4400 0.6
4500 0.577778
4600 0.6
4700 0.622222
4800 0.6
4900 0.577778
5000 0.6
5100 0.622222
5200 0.555556
5300 0.577778
5400 0.577778
5500 0.511111
5600 0.622222
5700 0.622222
5800 0.622222
5900 0.6
6000 0.6
6100 0.6
6200 0.577778
6300 0.6
6400 0.577778
6500 0.622222
6600 0.622222
6700 0.622222
6800 0.622222
6900 0.622222
7000 0.622222
7100 0.622222
7200 0.622222
7300 0.6
7400 0.6
7500 0.644444
7600 0.622222
7700 0.622222
7800 0.555556
7900 0

In [53]:
print "----TRAINING----"
train.print_classes()
print "----TESTING----"
test.print_classes()
print " "

images, labels = test.all()
output = y.eval(feed_dict={x: images, y_: labels})

for i in xrange(len(labels)):
    print output[i, :], labels[i, :]
    

----TRAINING----
dining_room 42
kitchen 44
living_room 57
----TESTING----
dining_room 15
kitchen 15
living_room 15
 
[ 0.30231684  0.49840146  0.19928175] [ 1.  0.  0.]
[ 0.75414973  0.03420987  0.21164039] [ 1.  0.  0.]
[ 0.53009123  0.00630179  0.46360695] [ 1.  0.  0.]
[ 0.08895306  0.04414973  0.86689723] [ 1.  0.  0.]
[ 0.49145713  0.09448324  0.41405967] [ 1.  0.  0.]
[ 0.15792133  0.33669835  0.50538027] [ 1.  0.  0.]
[ 0.50340033  0.22446702  0.27213261] [ 1.  0.  0.]
[ 0.2193546   0.12639134  0.65425408] [ 1.  0.  0.]
[ 0.45283031  0.35720786  0.18996187] [ 1.  0.  0.]
[ 0.4347299   0.23339711  0.33187303] [ 1.  0.  0.]
[ 0.21457192  0.55175823  0.23366983] [ 1.  0.  0.]
[ 0.43058586  0.12255517  0.446859  ] [ 1.  0.  0.]
[ 0.12194977  0.79452592  0.08352427] [ 1.  0.  0.]
[ 0.19788253  0.01151699  0.79060048] [ 1.  0.  0.]
[ 0.70173842  0.13774128  0.16052027] [ 1.  0.  0.]
[ 0.02044293  0.97801387  0.00154311] [ 0.  1.  0.]
[ 0.00754722  0.98883384  0.00361882] [ 0.  1.  0.]

In [8]:
batch = source.next_batch(20)
batch = source.all()

for i in xrange(20):
    print batch[1][i, :]
    print batch[0][i, :]

[ 1.  0.  0.]
[  25.   29.   30.   25.   22.   35.   35.   15.   29.   28.   32.   35.
   47.   35.   27.   37.   18.   27.   28.   35.   25.   27.   28.   22.
   25.    8.   22.   23.   32.   27.   29.   21.   36.   28.   40.   44.
   11.   38.   32.   53.   46.   39.   26.   32.   44.   31.   25.   32.
   22.   31.   31.   34.   15.   47.   26.   19.   45.   29.   35.   38.
   41.   33.   29.   40.   37.   18.   34.   40.   50.   42.   49.   30.
   31.   34.   18.   38.   27.   39.   31.    6.   38.   22.   21.   28.
   31.   39.   37.   22.   41.   43.   41.   54.   57.   40.   55.   58.
   51.   55.   47.   50.   33.   32.   33.   34.   29.   25.   26.   19.
   28.   27.   23.   31.   28.   33.   45.   44.   48.   34.   44.   41.
   40.   27.   24.   26.   51.   44.   48.   51.   57.   37.   32.   35.
   30.   34.   36.   16.   31.   32.   36.   32.   50.   35.   43.   52.
   36.   41.   76.   58.   43.   39.   59.   52.   55.   45.   40.   54.
   57.   38.   34.   32.   36.   48. 

In [9]:
batch[1]

array([[ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.